# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeachInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('come_time', models.DateField()),
                ('nick_name', models.CharField(max_length=128)),
            ],
        ),
    ]
